---
name: "DangerJS Github Action Harness"
author: "J. Patrick Fulton (jpfulton)"
description: "Runs DangerJS within a Docker container in a Github Action"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "check-square"
  color: "green"
inputs:
  dangerfile:
    description: "The path of the Dangerfile to run"
    required: true
  github_token:
    description: "The Github token to use for DangerJS"
    required: true
